spring.application.name=online-food-order-management-system
# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8081

# ===============================
# DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/food-system
spring.datasource.username=root
spring.datasource.password=TanyaGupta123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ===============================
# SPRING DATA REST
# ===============================
spring.data.rest.base-path=/api
